# 服务端口
server:
  port: 8888

# 服务名
spring:
  application:
    name: config
  # 文件系统存储方式来保存配置信息，默认从工程的src/main/resource目录下搜索配置文件
#  profiles:
#    active: ${active:native}
  # 配置中心
  cloud:
    config:
      server:
        # 配置仓库默认分支
        default-label: master
        git:
          # Git配置仓库默认分支
          default-label: master
          # Git配置仓库地址
          uri: https://github.com/longshunlin/cloudstu-dev/
          # 配置仓库路径
          # 开发环境
          search-paths:
  rabbitmq:
    host: 10.10.19.116
    port: 5672
    username: admin
    password: admin
#    stream:
#      kafka:
#        binder:
#          brokers: 47.104.96.68:9092
#          auto-create-topics: true
#          auto-add-partitions: true
#            bindings:
#              greetings-in:
#                destination: greetings
#                contentType: application/json
#              greetings-out:
#                destination: greetings
#                contentType: application/json

# Eureka
eureka:
  instance:
    # 以IP将本实例注册到注册中心
    prefer-ip-address: true
    # Eureka Server的注册表Status显示内容格式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 服务心跳时间间隔，默认为30
    lease-renewal-interval-in-seconds: 30
    # 服务过期时间，超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，默认为90
    # EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      # 单节点
      defaultZone: http://localhost:8761/eureka/
      # 集群
#      defaultZone: ${defaultZone:http://peer1:8761/eureka/,http://peer2:8761/eureka/,http://peer3:8761/eureka/}

# 刷新配置文件时不需要验证 curl -X POST http://localhost:8762/bus/refresh
#management:
#  security:
#    enabled: false
