server:
  port: 9994
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: auth-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/cloud_oauth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    filters: stat
#    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
#    poolPreparedStatements: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
#  redis:
#    host: 10.10.15.111
#    port: 6379

